# Generated by Django 4.1 on 2022-08-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_purchase_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='user',
            new_name='owner',
        ),
    ]
