# Generated by Django 4.1 on 2022-08-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_user_purchase_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='owner',
            new_name='user',
        ),
    ]
